<?php
return array(
	'title'      => esc_html__( 'Single Post Settings', 'buildexo' ),
	'id'         => 'single_post_setting',
	'desc'       => '',
	'subsection' => true,
	'fields'     => array(
		array(
			'id'      => 'single_source_type',
			'type'    => 'button_set',
			'title'   => esc_html__( 'Single Post Source Type', 'buildexo' ),
			'options' => array(
				'd' => esc_html__( 'Default', 'buildexo' ),
				'e' => esc_html__( 'Elementor', 'buildexo' ),
			),
			'default' => 'd',
		),
		array(
		    'id'       => 'single_elementor_template',
		    'type'     => 'select',
		    'title'    => __( 'Template', 'buildexo' ),
		    'options'     => 'posts',
		    'query_args'     => [
			    'post_type' => [ 'elementor_library' ],
				'posts_per_page'=> -1,
		    ],
		    'dependency' => [ 'single_source_type', '==', 'e' ],
	    ),
		array(
			'id'       => 'single_default_st',
			'type'     => 'heading',
			'content'    => esc_html__( 'Post Default', 'buildexo' ),
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'single_post_date',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Date', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show post publish date on posts detail page', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'single_post_author_box',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Author', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show author on posts detail page', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'single_post_comments',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Comments', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show number of comments on posts single page', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'single_post_tag',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Tags', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show post tags on posts single page', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'facebook_sharing',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Facebook Post Share', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show Post Share to Facebook', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'twitter_sharing',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Twitter Post Share', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show Post Share to Twitter', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'linkedin_sharing',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Linkedin Post Share', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show Post Share to Linkedin', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'pinterest_sharing',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Pinterest Post Share', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show Post Share to Pinterest', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'reddit_sharing',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Reddit Post Share', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show Post Share to Reddit', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'tumblr_sharing',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Tumblr Post Share', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show Post Share to Tumblr', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'      => 'digg_sharing',
			'type'    => 'switcher',
			'title'   => esc_html__( 'Show Digg Post Share', 'buildexo' ),
			'desc'    => esc_html__( 'Enable to show Post Share to Digg', 'buildexo' ),
			'default' => false,
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		//Social Media
		array(
			'id'       => 'show_single_post_author_social_share',
			'type'     => 'switcher',
			'title'    => esc_html__( 'Enable Social Media', 'buildexo' ),
			'desc'     => esc_html__( 'Enable/Disable Social Media.', 'buildexo' ),
			'default'  => '',
			'dependency' => array( 'single_source_type', '==', 'd' ),
		),
		array(
			'id'    => 'single_post_author_social_share',
			'type'  => 'repeater',
			'title' => esc_html__( 'Social Media', 'buildexo' ),
			'fields'	=> array(
				array(
					'id'       => 'url',
					'type'     => 'text',
					'title'    => esc_html__( 'URL', 'buildexo' ),
					'desc'     => esc_html__( 'Enter the URL of social Profile', 'buildexo' ),
				),
				array(
					'id'       => 'icon',
					'type'     => 'icon',
					'title'    => esc_html__( 'Icon', 'buildexo' ),
					'desc'     => esc_html__( 'Choose the icon', 'buildexo' ),
				),
				array(
					'id'       => 'color',
					'type'     => 'color',
					'title'    => esc_html__( 'Color', 'buildexo' ),
					'desc'     => esc_html__( 'Choose the color', 'buildexo' ),
				),
				array(
					'id'       => 'background',
					'type'     => 'color',
					'title'    => esc_html__( 'Background Color', 'buildexo' ),
					'desc'     => esc_html__( 'Choose the background color', 'buildexo' ),
				),
			),
			'dependency' => array(
				array( 'show_single_post_author_social_share', '==', true ),
			),			
		),		
	),
);
